### ISSUE TITLE
Too big method main()

### ISSUE THREAD

**Issue by JackVeromeev** [programming-653501/Yagorka#1]
In file Lab3_3.2.21.cpp. I guess, you can decompose it by creating some little functions.

**Comment by Shlyapnik** [comment]
Ok, I've got it. Thank you.

**Comment by Shlyapnik** [comment]
Lol, sorry, what? I have not file Lab3_3.2.21.cpp at all! I wrote in python.

**Comment by JackVeromeev** [comment]
_Dear @Shlyapnik !_
I created this issue in [repository of Yegor Nikolayenya](https://github.com/programming-653501/Yagorka), where file Lab3_3.2.21.cpp exists. Probably I had a mistake and created an issue in your repo, so I'm sorry. But even in address bar of my browser I see that this issue is referenced to "Yagorka" repository.
